-- =============================================================================
-- Procedure: [merge].[hq_fieldops.ProjectHub_Completion]
-- Description: Incremental update of field activity completion with hash-based change detection
-- Generated by: SQL Architect Agent
-- Created: 01/15/2026
-- WARNING: Review carefully before deploying to production
-- =============================================================================

CREATE PROCEDURE [merge].[hq_fieldops.ProjectHub_Completion]
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    
    DECLARE @ProcedureName NVARCHAR(255) = OBJECT_NAME(@@PROCID)
    DECLARE @AuditLogID BIGINT
    DECLARE @RowsInserted INT = 0
    DECLARE @RowsUpdated INT = 0
    DECLARE @RowsDeleted INT = 0
    DECLARE @ErrorMessage NVARCHAR(MAX)
    DECLARE @ErrorNumber INT
    DECLARE @ErrorSeverity INT
    DECLARE @ErrorState INT
    DECLARE @MergeOutput TABLE (Action NVARCHAR(10))
    
    INSERT INTO [EDW].[pipe].[ETL_AuditLog] (ProcedureName, StartDateTime, Status, db)
    VALUES (@ProcedureName, GETDATE(), 'Started', DB_NAME())
    
    SET @AuditLogID = SCOPE_IDENTITY()
    
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (SELECT 1 FROM [raw-hq].[projecthub].[field_activity_completion])
        BEGIN
            MERGE [EDW].[hq_fieldops].[ProjectHub_Completion] AS target
            USING (
                SELECT
                    p.id AS CompletionID,
                    p.project_id AS ProjectID,
                    CAST(p.activity_date AS DATE) AS ActivityDate,
                    p.status AS Status,
                    p.percentage AS Percentage,
                    HASHBYTES('SHA2_256',
                        CONCAT_WS('|',
                            ISNULL(CAST(p.id AS VARCHAR(8000)), '.'),
                            ISNULL(CAST(p.project_id AS VARCHAR(8000)), '.'),
                            ISNULL(CAST(p.activity_date AS VARCHAR(8000)), '.'),
                            ISNULL(CAST(p.status AS VARCHAR(8000)), '.'),
                            ISNULL(CAST(p.percentage AS VARCHAR(8000)), '.')
                        )
                    ) AS LoadHash,
                    GETDATE() AS CurrentDateTime
                FROM [raw-hq].[projecthub].[field_activity_completion] p
            ) AS source
            ON target.CompletionID = source.CompletionID
            
            WHEN MATCHED AND target.LoadHash <> source.LoadHash THEN
                UPDATE SET
                    target.ProjectID = source.ProjectID,
                    target.ActivityDate = source.ActivityDate,
                    target.Status = source.Status,
                    target.Percentage = source.Percentage,
                    target.LoadHash = source.LoadHash,
                    target.UpdateDateTime = source.CurrentDateTime
            
            WHEN NOT MATCHED BY TARGET THEN
                INSERT (CompletionID, ProjectID, ActivityDate, Status, Percentage, LoadHash, LoadDateTime, UpdateDateTime)
                VALUES (source.CompletionID, source.ProjectID, source.ActivityDate, source.Status, source.Percentage, source.LoadHash, source.CurrentDateTime, NULL)
            
            WHEN NOT MATCHED BY SOURCE THEN
                DELETE
            OUTPUT $action INTO @MergeOutput;
            
            SELECT @RowsInserted = COUNT(*) FROM @MergeOutput WHERE Action = 'INSERT';
            SELECT @RowsUpdated = COUNT(*) FROM @MergeOutput WHERE Action = 'UPDATE';
            SELECT @RowsDeleted = COUNT(*) FROM @MergeOutput WHERE Action = 'DELETE';

            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Success',
                RowsInserted = @RowsInserted, RowsUpdated = @RowsUpdated, RowsDeleted = @RowsDeleted
            WHERE AuditLogID = @AuditLogID;
        END
        ELSE
        BEGIN
            PRINT 'Source is empty. MERGE skipped to prevent accidental deletes.';
            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Skipped',
                RowsInserted = 0, RowsUpdated = 0, RowsDeleted = 0,
                ErrorMessage = 'Source empty - MERGE skipped'
            WHERE AuditLogID = @AuditLogID;
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        
        SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorNumber = ERROR_NUMBER(),
               @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE();

        UPDATE [EDW].[pipe].[ETL_AuditLog]
        SET EndDateTime = GETDATE(), Status = 'Failed',
            ErrorMessage = @ErrorMessage, ErrorNumber = @ErrorNumber,
            ErrorSeverity = @ErrorSeverity, ErrorState = @ErrorState
        WHERE AuditLogID = @AuditLogID;
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
