-- =============================================================================
-- Procedure: [create].[Fact/Dim]_[Entity]
-- Description: Initial creation and population of [Entity] table from EDW to Reporting layer
-- Generated by: [AI Agent Name]
-- Created: [Date]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [create].[Fact/Dim]_[Entity]
AS
BEGIN
    SET NOCOUNT ON;

    DROP TABLE IF EXISTS [fact/dim].[Entity];

    CREATE TABLE [fact/dim].[Entity] (
        [SurrogateKey] BIGINT NOT NULL,
        [DimensionKey] BIGINT NULL,
        [Measure1] DECIMAL(18,2) NULL,
        [LoadHash] VARBINARY(32) NOT NULL,
        [LoadDateTime] DATETIME2(7) NOT NULL,
        [UpdateDateTime] DATETIME2(7) NULL,
        CONSTRAINT [PK_Entity] PRIMARY KEY ([SurrogateKey] ASC)
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
              ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
        ) ON [PRIMARY]
    ) ON [PRIMARY];

    -- Insert transformed data into the target table
    INSERT INTO [fact/dim].[Entity] (
        [SurrogateKey], [DimensionKey], [Measure1], [LoadHash], [LoadDateTime]
    )
    SELECT
        source.[id] AS SurrogateKey,
        source.[dimension_key] AS DimensionKey,
        source.[measure1] AS Measure1,
        HASHBYTES('SHA2_256',
            CONCAT_WS('|',
                ISNULL(CAST(source.[id] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[dimension_key] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[measure1] AS VARCHAR(8000)), '')
            )
        ) AS LoadHash,
        GETDATE() AS LoadDateTime
    FROM [EDW].[schema].[SourceTable] source
END
GO
