-- =============================================================================
-- Procedure: [merge].[Fact/Dim].[Entity]
-- Description: Incremental update of [Entity] table with hash-based change detection
-- Generated by: [AI Agent Name]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [merge].[Fact/Dim.[Entity]]
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    
    DECLARE @ProcedureName NVARCHAR(255) = OBJECT_NAME(@@PROCID)
    DECLARE @AuditLogID BIGINT
    DECLARE @RowsInserted INT = 0
    DECLARE @RowsUpdated INT = 0
    DECLARE @RowsDeleted INT = 0
    DECLARE @ErrorMessage NVARCHAR(MAX)
    DECLARE @ErrorNumber INT
    DECLARE @ErrorSeverity INT
    DECLARE @ErrorState INT
    DECLARE @MergeOutput TABLE (Action NVARCHAR(10))
    
    INSERT INTO [EDW].[pipe].[ETL_AuditLog] (ProcedureName, StartDateTime, Status, db)
    VALUES (@ProcedureName, GETDATE(), 'Started', db_name())
    SET @AuditLogID = SCOPE_IDENTITY()
    
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (SELECT 1 FROM [EDW].[schema].[SourceTable])
        BEGIN
            MERGE [database].[fact/dim].[Entity] AS target
            USING (
                SELECT [id], [column1], [measure1],
                    HASHBYTES('SHA2_256',
                        CONCAT_WS('|',
                            ISNULL(CAST([id] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([column1] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([measure1] AS VARCHAR(8000)), '')
                        )
                    ) AS LoadHash,
                    GETDATE() AS CurrentDateTime
                FROM [EDW].[schema].[SourceTable]
            ) AS source 
            ON target.[PrimaryKey] = source.[id]
            
            WHEN MATCHED AND target.LoadHash <> source.LoadHash THEN
                UPDATE SET target.column1 = source.column1, target.measure1 = source.measure1,
                    target.LoadHash = source.LoadHash, target.UpdateDateTime = source.CurrentDateTime
            
            WHEN NOT MATCHED BY TARGET THEN
                INSERT ([id], [column1], [measure1], [LoadHash], [LoadDateTime], [UpdateDateTime])
                VALUES (source.[id], source.column1, source.measure1, source.LoadHash, source.CurrentDateTime, NULL)
            
            WHEN NOT MATCHED BY SOURCE THEN DELETE
            OUTPUT $action INTO @MergeOutput;
            
            SELECT @RowsInserted = COUNT(*) FROM @MergeOutput WHERE Action = 'INSERT'
            SELECT @RowsUpdated = COUNT(*) FROM @MergeOutput WHERE Action = 'UPDATE'
            SELECT @RowsDeleted = COUNT(*) FROM @MergeOutput WHERE Action = 'DELETE'

            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Success',
                RowsInserted = @RowsInserted, RowsUpdated = @RowsUpdated, RowsDeleted = @RowsDeleted
            WHERE AuditLogID = @AuditLogID;
        END
        ELSE
        BEGIN
            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Skipped',
                ErrorMessage = 'Source empty - MERGE skipped'
            WHERE AuditLogID = @AuditLogID;
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorNumber = ERROR_NUMBER(),
               @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE();
        UPDATE [EDW].[pipe].[ETL_AuditLog]
        SET EndDateTime = GETDATE(), Status = 'Failed',
            ErrorMessage = @ErrorMessage, ErrorNumber = @ErrorNumber,
            ErrorSeverity = @ErrorSeverity, ErrorState = @ErrorState
        WHERE AuditLogID = @AuditLogID;
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
GO
