-- =============================================================================
-- Procedure: [create].[org]_[subject]_[SourceSystem]_[Entity]
-- Description: Initial creation and population of [Entity] table from raw to EDW
-- Generated by: [AI Agent Name] (e.g., SQL Architect Agent)
-- Created: [Date] (e.g., 01/15/2026)
-- Reviewed By: [User Name or Account]
-- Modified: [Date] [User Name or Account] - [Description of changes]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

CREATE PROCEDURE [create].[org_subject_SourceSystem_Entity]
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop existing table if it exists
    DROP TABLE IF EXISTS [org_subject].[SourceSystem_Entity];

    -- Create table structure
    CREATE TABLE [org_subject].[SourceSystem_Entity] (
        [PKColumn] BIGINT NOT NULL,
        [Column2] VARCHAR(255) NULL,
        [Column3] VARCHAR(255) NULL,
        -- ... additional columns ...
        [LoadHash] VARBINARY(32) NOT NULL,
        [LoadDateTime] DATETIME2(7) NOT NULL,
        [UpdateDateTime] DATETIME2(7) NULL,
        CONSTRAINT [PK_SourceSystem_Entity] PRIMARY KEY (
            [PKColumn] ASC
        ) WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON,
        OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
        ) ON [PRIMARY]
    ) ON [PRIMARY];

    -- Use CTE for data transformation
    WITH _[SourceSystem][Entity] AS (
        SELECT
            p.source_col1 AS PKColumn,
            p.source_col2 AS Column2,
            p.source_col3 AS Column3,
            -- ... additional columns ...
            HASHBYTES('SHA2_256',
                CONCAT_WS('|',
                    ISNULL(CAST(p.source_col1 AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.source_col2 AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.source_col3 AS VARCHAR(8000)), '.')
                    -- Include all relevant columns
                )
            ) AS LoadHash,
            GETDATE() AS LoadDateTime
        FROM [raw].[source].[table] p
    )

    -- Insert transformed data into the target table
    INSERT INTO [org_subject].[SourceSystem_Entity] (
        [PKColumn],
        [Column2],
        [Column3],
        -- ... all columns ...
        [LoadHash],
        [LoadDateTime]
    )
    SELECT
        PKColumn,
        Column2,
        Column3,
        -- ... all columns ...
        LoadHash,
        LoadDateTime
    FROM _[SourceSystem][Entity];
END
