-- =============================================================================
-- Procedure: [merge].[org]_[subject].[SourceSystem]_[Entity]
-- Description: Incremental update of [Entity] table with hash-based change detection
-- Generated by: [AI Agent Name]
-- Created: [Date]
-- Reviewed By: [User Name or Account]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

CREATE PROCEDURE [merge].[org_subject.SourceSystem_Entity]
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    
    DECLARE @ProcedureName NVARCHAR(255) = OBJECT_NAME(@@PROCID)
    DECLARE @AuditLogID BIGINT
    DECLARE @RowsInserted INT = 0
    DECLARE @RowsUpdated INT = 0
    DECLARE @RowsDeleted INT = 0
    DECLARE @ErrorMessage NVARCHAR(MAX)
    DECLARE @ErrorNumber INT
    DECLARE @ErrorSeverity INT
    DECLARE @ErrorState INT
    DECLARE @MergeOutput TABLE (Action NVARCHAR(10))
    
    INSERT INTO [EDW].[pipe].[ETL_AuditLog] (ProcedureName, StartDateTime, Status, db)
    VALUES (@ProcedureName, GETDATE(), 'Started', DB_NAME())
    
    SET @AuditLogID = SCOPE_IDENTITY()
    
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (SELECT 1 FROM [raw].[source_schema].[source_table])
        BEGIN
            MERGE [EDW].[org_subject].[SourceSystem_Entity] AS target
            USING (
                SELECT
                    p.source_col1 AS PKColumn,
                    p.source_col2 AS Column2,
                    HASHBYTES('SHA2_256',
                        CONCAT_WS('|',
                            ISNULL(CAST(p.source_col1 AS VARCHAR(8000)), '.'),
                            ISNULL(CAST(p.source_col2 AS VARCHAR(8000)), '.')
                        )
                    ) AS LoadHash,
                    GETDATE() AS CurrentDateTime
                FROM [raw].[source_schema].[source_table] p
            ) AS source
            ON target.PKColumn = source.PKColumn
            
            WHEN MATCHED AND target.LoadHash <> source.LoadHash THEN
                UPDATE SET
                    target.Column2 = source.Column2,
                    target.LoadHash = source.LoadHash,
                    target.UpdateDateTime = source.CurrentDateTime
            
            WHEN NOT MATCHED BY TARGET THEN
                INSERT (PKColumn, Column2, LoadHash, LoadDateTime, UpdateDateTime)
                VALUES (source.PKColumn, source.Column2, source.LoadHash, source.CurrentDateTime, NULL)
            
            WHEN NOT MATCHED BY SOURCE THEN
                DELETE
            OUTPUT $action INTO @MergeOutput;
            
            SELECT @RowsInserted = COUNT(*) FROM @MergeOutput WHERE Action = 'INSERT';
            SELECT @RowsUpdated = COUNT(*) FROM @MergeOutput WHERE Action = 'UPDATE';
            SELECT @RowsDeleted = COUNT(*) FROM @MergeOutput WHERE Action = 'DELETE';

            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Success',
                RowsInserted = @RowsInserted, RowsUpdated = @RowsUpdated, RowsDeleted = @RowsDeleted
            WHERE AuditLogID = @AuditLogID;
        END
        ELSE
        BEGIN
            PRINT 'Source is empty. MERGE skipped to prevent accidental deletes.';
            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Skipped',
                RowsInserted = 0, RowsUpdated = 0, RowsDeleted = 0,
                ErrorMessage = 'Source empty - MERGE skipped'
            WHERE AuditLogID = @AuditLogID;
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        
        SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorNumber = ERROR_NUMBER(),
               @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE();

        UPDATE [EDW].[pipe].[ETL_AuditLog]
        SET EndDateTime = GETDATE(), Status = 'Failed',
            ErrorMessage = @ErrorMessage, ErrorNumber = @ErrorNumber,
            ErrorSeverity = @ErrorSeverity, ErrorState = @ErrorState
        WHERE AuditLogID = @AuditLogID;
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
