-- =============================================================================
-- Procedure: [create].[hq_fieldops_ProjectHub_Completion]
-- Description: Initial creation and population of field activity completion table from raw to EDW
-- Generated by: SQL Architect Agent
-- Created: 01/15/2026
-- Reviewed By: Your Name
-- Modified: [Not yet modified]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

CREATE PROCEDURE [create].[hq_fieldops_ProjectHub_Completion]
AS
BEGIN
    SET NOCOUNT ON;

    DROP TABLE IF EXISTS [hq_fieldops].[ProjectHub_Completion];

    CREATE TABLE [hq_fieldops].[ProjectHub_Completion] (
        [CompletionID] BIGINT NOT NULL,
        [ProjectID] BIGINT NULL,
        [ActivityDate] DATE NULL,
        [Status] VARCHAR(50) NULL,
        [Percentage] DECIMAL(5,2) NULL,
        [LoadHash] VARBINARY(32) NOT NULL,
        [LoadDateTime] DATETIME2(7) NOT NULL,
        [UpdateDateTime] DATETIME2(7) NULL,
        CONSTRAINT [PK_ProjectHub_Completion] PRIMARY KEY ([CompletionID] ASC)
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
              ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
        ) ON [PRIMARY]
    ) ON [PRIMARY];

    WITH _ProjectHubCompletion AS (
        SELECT
            p.id AS CompletionID,
            p.project_id AS ProjectID,
            CAST(p.activity_date AS DATE) AS ActivityDate,
            p.status AS Status,
            p.percentage AS Percentage,
            HASHBYTES('SHA2_256',
                CONCAT_WS('|',
                    ISNULL(CAST(p.id AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.project_id AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.activity_date AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.status AS VARCHAR(8000)), '.'),
                    ISNULL(CAST(p.percentage AS VARCHAR(8000)), '.')
                )
            ) AS LoadHash,
            GETDATE() AS LoadDateTime
        FROM [raw-hq].[projecthub].[field_activity_completion] p
    )

    -- Insert transformed data into the target table
    INSERT INTO [hq_fieldops].[ProjectHub_Completion] (
        [CompletionID],
        [ProjectID],
        [ActivityDate],
        [Status],
        [Percentage],
        [LoadHash],
        [LoadDateTime]
    )
    SELECT
        CompletionID,
        ProjectID,
        ActivityDate,
        Status,
        Percentage,
        LoadHash,
        LoadDateTime
    FROM _ProjectHubCompletion;
END
