-- =============================================================================
-- Procedure: [create].[Fact_ComplianceAudits]
-- Description: Initial creation and population of compliance audits fact table
-- Generated by: SQL Architect Agent
-- Created: 01/15/2026
-- WARNING: Review carefully before deploying to production
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [create].[Fact_ComplianceAudits]
AS
BEGIN
    SET NOCOUNT ON;

    DROP TABLE IF EXISTS [fact].[ComplianceAudits];

    CREATE TABLE [fact].[ComplianceAudits] (
        [AuditID]               BIGINT        NOT NULL,
        [ProjectID]             BIGINT        NOT NULL,
        [AuditName]             VARCHAR(255)  NULL,
        [Status]                VARCHAR(255)  NULL,
        [Overdue]               BIT           NULL,
        [Category]              VARCHAR(255)  NULL,
        [AuditDate]             DATE          NULL,
        [DueDate]               DATE          NULL,
        [DateClosed]            DATE          NULL,
        [ConformingCount]       BIGINT        NULL,
        [DeficientCount]        BIGINT        NULL,
        [TotalItemsCount]       BIGINT        NULL,
        [LoadHash]              VARBINARY(32) NOT NULL,
        [LoadDateTime]          DATETIME2(7)  NOT NULL,
        [UpdateDateTime]        DATETIME2(7)  NULL,
        CONSTRAINT [PK_FactComplianceAudits] PRIMARY KEY ([AuditID] ASC)
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
              ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
        ) ON [PRIMARY]
    ) ON [PRIMARY];

    -- Insert transformed data into the target table
    INSERT INTO [fact].[ComplianceAudits] (
        [AuditID], [ProjectID], [AuditName], [Status], [Overdue],
        [Category], [AuditDate], [DueDate], [DateClosed],
        [ConformingCount], [DeficientCount], [TotalItemsCount],
        [LoadHash], [LoadDateTime]
    )
    SELECT
        a.[AuditID],
        a.[ProjectID],
        a.[AuditName],
        a.[Status],
        a.[Overdue],
        a.[AuditCategory] AS Category,
        a.[AuditDate],
        a.[DueDate],
        a.[DateClosed],
        a.[ConformingCount],
        a.[DeficientCount],
        a.[TotalItemsCount],
        HASHBYTES('SHA2_256',
            CONCAT_WS('|',
                ISNULL(CAST(a.[AuditID] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[ProjectID] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[AuditName] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[Status] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[Overdue] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[AuditCategory] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[AuditDate] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[DueDate] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[DateClosed] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[ConformingCount] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[DeficientCount] AS VARCHAR(8000)), ''),
                ISNULL(CAST(a.[TotalItemsCount] AS VARCHAR(8000)), '')
            )
        ) AS LoadHash,
        GETDATE() AS LoadDateTime
    FROM [EDW].[hq_compliance].[SafeTrack_Audits] a
END
GO
