-- =============================================================================
-- Procedure: [create].[Fact/Dim]_[Entity]
-- Description: Initial creation and population of [Entity] dimension/fact table from EDW to Reporting layer
-- Generated by: [AI Agent Name] (e.g., SQL Architect Agent)
-- Created: [Date] (e.g., 01/15/2026)
-- Reviewed By: [User Name or Account]
-- Modified: [Not yet modified]
-- WARNING: Review carefully before deploying to production
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [create].[Fact/Dim]_[Entity]
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop existing table if it exists
    DROP TABLE IF EXISTS [Fact/Dim].[Entity];

    -- Create table structure
    CREATE TABLE [Fact/Dim].[Entity] (
        [SurrogateKey] BIGINT NOT NULL,
        [DimensionKey] BIGINT NULL,            
        [Column1] VARCHAR(255) NULL,
        [Column2] VARCHAR(255) NULL,
        [Column3] BIGINT NULL,                
        [Column4] DECIMAL(18,2) NULL,         
        [LoadHash] VARBINARY(32) NOT NULL,
        [LoadDateTime] DATETIME2(7) NOT NULL,
        [UpdateDateTime] DATETIME2(7) NULL,
        CONSTRAINT [PK_Entity] PRIMARY KEY  (
            [SurrogateKey] ASC
        ) WITH (
            PAD_INDEX = OFF,
            STATISTICS_NORECOMPUTE = OFF,
            IGNORE_DUP_KEY = OFF,
            ALLOW_ROW_LOCKS = ON,
            ALLOW_PAGE_LOCKS = ON,
            OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
        ) ON [PRIMARY]
    ) ON [PRIMARY];

    -- Insert transformed data into the target table
    INSERT INTO [Fact/Dim].[Entity] (
        [SurrogateKey],
        [DimensionKey],
        [Column1],
        [Column2],
        [Column3],
        [Column4],
        [LoadHash],
        [LoadDateTime]
    )
    SELECT
        source.[id] AS SurrogateKey,
        dim.[DimensionKey] AS DimensionKey,
        source.[column1] AS Column1,
        source.[column2] AS Column2,
        source.[column3] AS Column3,
        source.[column4] AS Column4,
        HASHBYTES('SHA2_256',
            CONCAT_WS('|',
                ISNULL(CAST(source.[id] AS VARCHAR(8000)), ''),
                ISNULL(CAST(dim.[DimensionKey] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[column1] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[column2] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[column3] AS VARCHAR(8000)), ''),
                ISNULL(CAST(source.[column4] AS VARCHAR(8000)), '')
            )
        ) AS LoadHash,
        GETDATE() AS LoadDateTime
    FROM [EDW].[schema].[SourceTable] source
END
GO
