-- =============================================================================
-- Procedure: [merge].[Fact.ComplianceAudits]
-- Description: Incremental update of compliance audits fact table
-- Generated by: SQL Architect Agent
-- Created: 01/15/2026
-- WARNING: Review carefully before deploying to production
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [merge].[Fact.ComplianceAudits]
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    
    DECLARE @ProcedureName NVARCHAR(255) = OBJECT_NAME(@@PROCID)
    DECLARE @AuditLogID BIGINT
    DECLARE @RowsInserted INT = 0
    DECLARE @RowsUpdated INT = 0
    DECLARE @RowsDeleted INT = 0
    DECLARE @ErrorMessage NVARCHAR(MAX)
    DECLARE @ErrorNumber INT
    DECLARE @ErrorSeverity INT
    DECLARE @ErrorState INT
    DECLARE @MergeOutput TABLE (Action NVARCHAR(10))
    
    INSERT INTO [EDW].[pipe].[ETL_AuditLog] (ProcedureName, StartDateTime, Status, db)
    VALUES (@ProcedureName, GETDATE(), 'Started', db_name())
    SET @AuditLogID = SCOPE_IDENTITY()
    
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (SELECT 1 FROM [EDW].[hq_compliance].[SafeTrack_Audits])
        BEGIN
            MERGE [reporting-hq].[fact].[ComplianceAudits] AS target
            USING (
                SELECT
                    [AuditID], [ProjectID], [AuditName], [Status], [Overdue],
                    [AuditCategory] AS Category, [AuditDate], [DueDate], [DateClosed],
                    [ConformingCount], [DeficientCount], [TotalItemsCount],
                    HASHBYTES('SHA2_256',
                        CONCAT_WS('|',
                            ISNULL(CAST([AuditID] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([ProjectID] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([AuditName] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([Status] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([Overdue] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([AuditCategory] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([AuditDate] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([DueDate] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([DateClosed] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([ConformingCount] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([DeficientCount] AS VARCHAR(8000)), ''),
                            ISNULL(CAST([TotalItemsCount] AS VARCHAR(8000)), '')
                        )
                    ) AS LoadHash,
                    GETDATE() AS CurrentDateTime
                FROM [EDW].[hq_compliance].[SafeTrack_Audits]
            ) AS source 
            ON target.[AuditID] = source.[AuditID]
            
            WHEN MATCHED AND target.LoadHash <> source.LoadHash THEN
                UPDATE SET
                    target.ProjectID = source.ProjectID, target.AuditName = source.AuditName,
                    target.Status = source.Status, target.Overdue = source.Overdue,
                    target.Category = source.Category, target.AuditDate = source.AuditDate,
                    target.DueDate = source.DueDate, target.DateClosed = source.DateClosed,
                    target.ConformingCount = source.ConformingCount,
                    target.DeficientCount = source.DeficientCount,
                    target.TotalItemsCount = source.TotalItemsCount,
                    target.LoadHash = source.LoadHash, target.UpdateDateTime = source.CurrentDateTime
            
            WHEN NOT MATCHED BY TARGET THEN
                INSERT ([AuditID], [ProjectID], [AuditName], [Status], [Overdue], [Category],
                        [AuditDate], [DueDate], [DateClosed], [ConformingCount], [DeficientCount],
                        [TotalItemsCount], [LoadHash], [LoadDateTime], [UpdateDateTime])
                VALUES (source.AuditID, source.ProjectID, source.AuditName, source.Status,
                        source.Overdue, source.Category, source.AuditDate, source.DueDate,
                        source.DateClosed, source.ConformingCount, source.DeficientCount,
                        source.TotalItemsCount, source.LoadHash, source.CurrentDateTime, NULL)
            
            WHEN NOT MATCHED BY SOURCE THEN DELETE
            OUTPUT $action INTO @MergeOutput;
            
            SELECT @RowsInserted = COUNT(*) FROM @MergeOutput WHERE Action = 'INSERT'
            SELECT @RowsUpdated = COUNT(*) FROM @MergeOutput WHERE Action = 'UPDATE'
            SELECT @RowsDeleted = COUNT(*) FROM @MergeOutput WHERE Action = 'DELETE'

            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Success',
                RowsInserted = @RowsInserted, RowsUpdated = @RowsUpdated, RowsDeleted = @RowsDeleted
            WHERE AuditLogID = @AuditLogID;
        END
        ELSE
        BEGIN
            UPDATE [EDW].[pipe].[ETL_AuditLog]
            SET EndDateTime = GETDATE(), Status = 'Skipped',
                ErrorMessage = 'Source empty - MERGE skipped'
            WHERE AuditLogID = @AuditLogID;
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorNumber = ERROR_NUMBER(),
               @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE();
        UPDATE [EDW].[pipe].[ETL_AuditLog]
        SET EndDateTime = GETDATE(), Status = 'Failed',
            ErrorMessage = @ErrorMessage, ErrorNumber = @ErrorNumber,
            ErrorSeverity = @ErrorSeverity, ErrorState = @ErrorState
        WHERE AuditLogID = @AuditLogID;
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
GO
